// src/code-snippet/react/query.js
import React from 'react';
import gql from 'graphql-tag';
import { graphql } from 'react-apollo';

// The data prop, which is provided by the wrapper below contains,
// a `loading` key while the query is in flight and posts when it is ready
function PostList({ data: { loading, posts } }) {
  if (loading) {
    return <div>Loading</div>;
  } else {
    return (
      <ul>
        {posts.map(post =>
          <li key={post.id}>
            {post.title} by {' '}
            {post.author.firstName} {post.author.lastName} {' '}
            ({post.votes} votes)
          </li>
        )}
      </ul>
    );
  }
}

// The `graphql` wrapper executes a GraphQL query and makes the results
// available on the `data` prop of the wrapped component (PostList here)
export default graphql(gql`
  query allPosts {
    posts {
      id
      title
      votes
      author {
        id
        firstName
        lastName
      }
    }
  }
`)(PostList);

// src/code-snippet/angular/query.js
import { Component, OnInit } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

@Component({
  selector: 'post-list',
  template: `
    <div *ngIf="loading">Loading</div>
    <ul *ngIf="!loading">
      <li *ngFor="let post of posts">
        {{post.title}} by 
        {{post.author.firstName}} {{post.author.lastName}}
        ({{post.votes}} votes)
      </li>
    </ul>
  `
})
class PostListComponent implements OnInit {
  loading: boolean;
  posts: any[];

  constructor(private apollo: Apollo) {}

  ngOnInit() {
    this.apollo.watchQuery({
      query: gql`
        query allPosts {
          posts {
            id
            title
            votes
            author {
              id
              firstName
              lastName
            }
          }
        }
      `
    }).subscribe(({ loading, data }) => {
      this.loading = loading;
      this.posts = data.posts;
    });
  }
}
